version: '3'
services:

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8080"
    environment:
#      - SPRING_PROFILES_ACTIVE=production
#      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - /tmp
    depends_on:
      db:
        condition: service_started

volumes:
  db-data:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: ./database-storage
  tmp: